//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.02 at 11:33:10 PM CEST 
//


package com.megatravel.agentbackend.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accommodation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accommodation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acc_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="acc_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acc_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acc_capacity">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="acc_pictures" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded"/>
 *         &lt;element name="acc_price_plan" type="{http://megatravel.com/booking}acc_price" maxOccurs="unbounded"/>
 *         &lt;element name="acc_unavailable" type="{http://megatravel.com/booking}acc_unavailable"/>
 *         &lt;element name="acc_location" type="{http://megatravel.com/booking}acc_location"/>
 *         &lt;element name="acc_category" type="{http://megatravel.com/booking}category"/>
 *         &lt;element name="acc_type" type="{http://megatravel.com/booking}acc_type"/>
 *         &lt;element name="acc_services" type="{http://megatravel.com/booking}service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="acc_agent" type="{http://megatravel.com/booking}user"/>
 *         &lt;element name="acc_cancel_period">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="acc_avg_rating">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accommodation", propOrder = {
    "accId",
    "accName",
    "accDescription",
    "accCapacity",
    "accPictures",
    "accPricePlan",
    "accUnavailable",
    "accLocation",
    "accCategory",
    "accType",
    "accServices",
    "accAgent",
    "accCancelPeriod",
    "accAvgRating"
})
public class Accommodation {

    @XmlElement(name = "acc_id")
    protected long accId;
    @XmlElement(name = "acc_name", required = true)
    protected String accName;
    @XmlElement(name = "acc_description", required = true)
    protected String accDescription;
    @XmlElement(name = "acc_capacity")
    protected int accCapacity;
    @XmlElement(name = "acc_pictures", required = true)
    protected List<byte[]> accPictures;
    @XmlElement(name = "acc_price_plan", required = true)
    protected List<AccPrice> accPricePlan;
    @XmlElement(name = "acc_unavailable", required = true)
    protected AccUnavailable accUnavailable;
    @XmlElement(name = "acc_location", required = true)
    protected AccLocation accLocation;
    @XmlElement(name = "acc_category", required = true)
    protected Category accCategory;
    @XmlElement(name = "acc_type", required = true)
    protected AccType accType;
    @XmlElement(name = "acc_services")
    protected List<Service> accServices;
    @XmlElement(name = "acc_agent", required = true)
    protected User accAgent;
    @XmlElement(name = "acc_cancel_period")
    protected int accCancelPeriod;
    @XmlElement(name = "acc_avg_rating", defaultValue = "0")
    protected float accAvgRating;

    /**
     * Gets the value of the accId property.
     * 
     */
    public long getAccId() {
        return accId;
    }

    /**
     * Sets the value of the accId property.
     * 
     */
    public void setAccId(long value) {
        this.accId = value;
    }

    /**
     * Gets the value of the accName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccName() {
        return accName;
    }

    /**
     * Sets the value of the accName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccName(String value) {
        this.accName = value;
    }

    /**
     * Gets the value of the accDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccDescription() {
        return accDescription;
    }

    /**
     * Sets the value of the accDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccDescription(String value) {
        this.accDescription = value;
    }

    /**
     * Gets the value of the accCapacity property.
     * 
     */
    public int getAccCapacity() {
        return accCapacity;
    }

    /**
     * Sets the value of the accCapacity property.
     * 
     */
    public void setAccCapacity(int value) {
        this.accCapacity = value;
    }

    /**
     * Gets the value of the accPictures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accPictures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccPictures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * byte[]
     * 
     */
    public List<byte[]> getAccPictures() {
        if (accPictures == null) {
            accPictures = new ArrayList<byte[]>();
        }
        return this.accPictures;
    }

    /**
     * Gets the value of the accPricePlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accPricePlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccPricePlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccPrice }
     * 
     * 
     */
    public List<AccPrice> getAccPricePlan() {
        if (accPricePlan == null) {
            accPricePlan = new ArrayList<AccPrice>();
        }
        return this.accPricePlan;
    }

    /**
     * Gets the value of the accUnavailable property.
     * 
     * @return
     *     possible object is
     *     {@link AccUnavailable }
     *     
     */
    public AccUnavailable getAccUnavailable() {
        return accUnavailable;
    }

    /**
     * Sets the value of the accUnavailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccUnavailable }
     *     
     */
    public void setAccUnavailable(AccUnavailable value) {
        this.accUnavailable = value;
    }

    /**
     * Gets the value of the accLocation property.
     * 
     * @return
     *     possible object is
     *     {@link AccLocation }
     *     
     */
    public AccLocation getAccLocation() {
        return accLocation;
    }

    /**
     * Sets the value of the accLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccLocation }
     *     
     */
    public void setAccLocation(AccLocation value) {
        this.accLocation = value;
    }

    /**
     * Gets the value of the accCategory property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getAccCategory() {
        return accCategory;
    }

    /**
     * Sets the value of the accCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setAccCategory(Category value) {
        this.accCategory = value;
    }

    /**
     * Gets the value of the accType property.
     * 
     * @return
     *     possible object is
     *     {@link AccType }
     *     
     */
    public AccType getAccType() {
        return accType;
    }

    /**
     * Sets the value of the accType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccType }
     *     
     */
    public void setAccType(AccType value) {
        this.accType = value;
    }

    /**
     * Gets the value of the accServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getAccServices() {
        if (accServices == null) {
            accServices = new ArrayList<Service>();
        }
        return this.accServices;
    }

    /**
     * Gets the value of the accAgent property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getAccAgent() {
        return accAgent;
    }

    /**
     * Sets the value of the accAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setAccAgent(User value) {
        this.accAgent = value;
    }

    /**
     * Gets the value of the accCancelPeriod property.
     * 
     */
    public int getAccCancelPeriod() {
        return accCancelPeriod;
    }

    /**
     * Sets the value of the accCancelPeriod property.
     * 
     */
    public void setAccCancelPeriod(int value) {
        this.accCancelPeriod = value;
    }

    /**
     * Gets the value of the accAvgRating property.
     * 
     */
    public float getAccAvgRating() {
        return accAvgRating;
    }

    /**
     * Sets the value of the accAvgRating property.
     * 
     */
    public void setAccAvgRating(float value) {
        this.accAvgRating = value;
    }

}
