//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 08:08:22 PM CEST 
//


package com.megatravel.agentbackend.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acc_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="acc_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acc_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acc_capacity">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="acc_pictures">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="acc_picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acc_price_plan">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="acc_price" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="price_value" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="price_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="price_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acc_unavailable">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="unavailable_start" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="unavailable_end" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acc_location">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}category"/>
 *         &lt;element ref="{}acc_type"/>
 *         &lt;element name="acc_services">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}service" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}agent"/>
 *         &lt;element name="acc_cancel_period">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="acc_avg_rating">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accId",
    "accName",
    "accDescription",
    "accCapacity",
    "accPictures",
    "accPricePlan",
    "accUnavailable",
    "accLocation",
    "category",
    "accType",
    "accServices",
    "agent",
    "accCancelPeriod",
    "accAvgRating"
})
@XmlRootElement(name = "accommodation")
@Entity
public class Accommodation {
	
	@Id
    @XmlElement(name = "acc_id")
    protected long accId;
    @XmlElement(name = "acc_name", required = true)
    protected String accName;
    @XmlElement(name = "acc_description", required = true)
    protected String accDescription;
    @XmlElement(name = "acc_capacity")
    protected int accCapacity;
    @XmlElement(name = "acc_pictures", required = true)
    protected Accommodation.AccPictures accPictures;
    @XmlElement(name = "acc_price_plan", required = true)
    protected Accommodation.AccPricePlan accPricePlan;
    @XmlElement(name = "acc_unavailable", required = true)
    protected Accommodation.AccUnavailable accUnavailable;
    @XmlElement(name = "acc_location", required = true)
    protected Accommodation.AccLocation accLocation;
    @XmlElement(required = true)
    protected Category category;
    @XmlElement(name = "acc_type", required = true)
    protected AccType accType;
    @XmlElement(name = "acc_services", required = true)
    protected Accommodation.AccServices accServices;
    @XmlElement(required = true)
    protected Agent agent;
    @XmlElement(name = "acc_cancel_period")
    protected int accCancelPeriod;
    @XmlElement(name = "acc_avg_rating", defaultValue = "0")
    protected float accAvgRating;

    /**
     * Gets the value of the accId property.
     * 
     */
    public long getAccId() {
        return accId;
    }

    /**
     * Sets the value of the accId property.
     * 
     */
    public void setAccId(long value) {
        this.accId = value;
    }

    /**
     * Gets the value of the accName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccName() {
        return accName;
    }

    /**
     * Sets the value of the accName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccName(String value) {
        this.accName = value;
    }

    /**
     * Gets the value of the accDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccDescription() {
        return accDescription;
    }

    /**
     * Sets the value of the accDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccDescription(String value) {
        this.accDescription = value;
    }

    /**
     * Gets the value of the accCapacity property.
     * 
     */
    public int getAccCapacity() {
        return accCapacity;
    }

    /**
     * Sets the value of the accCapacity property.
     * 
     */
    public void setAccCapacity(int value) {
        this.accCapacity = value;
    }

    /**
     * Gets the value of the accPictures property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation.AccPictures }
     *     
     */
    public Accommodation.AccPictures getAccPictures() {
        return accPictures;
    }

    /**
     * Sets the value of the accPictures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation.AccPictures }
     *     
     */
    public void setAccPictures(Accommodation.AccPictures value) {
        this.accPictures = value;
    }

    /**
     * Gets the value of the accPricePlan property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation.AccPricePlan }
     *     
     */
    public Accommodation.AccPricePlan getAccPricePlan() {
        return accPricePlan;
    }

    /**
     * Sets the value of the accPricePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation.AccPricePlan }
     *     
     */
    public void setAccPricePlan(Accommodation.AccPricePlan value) {
        this.accPricePlan = value;
    }

    /**
     * Gets the value of the accUnavailable property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation.AccUnavailable }
     *     
     */
    public Accommodation.AccUnavailable getAccUnavailable() {
        return accUnavailable;
    }

    /**
     * Sets the value of the accUnavailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation.AccUnavailable }
     *     
     */
    public void setAccUnavailable(Accommodation.AccUnavailable value) {
        this.accUnavailable = value;
    }

    /**
     * Gets the value of the accLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation.AccLocation }
     *     
     */
    public Accommodation.AccLocation getAccLocation() {
        return accLocation;
    }

    /**
     * Sets the value of the accLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation.AccLocation }
     *     
     */
    public void setAccLocation(Accommodation.AccLocation value) {
        this.accLocation = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the accType property.
     * 
     * @return
     *     possible object is
     *     {@link AccType }
     *     
     */
    public AccType getAccType() {
        return accType;
    }

    /**
     * Sets the value of the accType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccType }
     *     
     */
    public void setAccType(AccType value) {
        this.accType = value;
    }

    /**
     * Gets the value of the accServices property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation.AccServices }
     *     
     */
    public Accommodation.AccServices getAccServices() {
        return accServices;
    }

    /**
     * Sets the value of the accServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation.AccServices }
     *     
     */
    public void setAccServices(Accommodation.AccServices value) {
        this.accServices = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link Agent }
     *     
     */
    public Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agent }
     *     
     */
    public void setAgent(Agent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the accCancelPeriod property.
     * 
     */
    public int getAccCancelPeriod() {
        return accCancelPeriod;
    }

    /**
     * Sets the value of the accCancelPeriod property.
     * 
     */
    public void setAccCancelPeriod(int value) {
        this.accCancelPeriod = value;
    }

    /**
     * Gets the value of the accAvgRating property.
     * 
     */
    public float getAccAvgRating() {
        return accAvgRating;
    }

    /**
     * Sets the value of the accAvgRating property.
     * 
     */
    public void setAccAvgRating(float value) {
        this.accAvgRating = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address",
        "city",
        "country",
        "latitude",
        "longitude"
    })
    public static class AccLocation {

        @XmlElement(required = true)
        protected String address;
        @XmlElement(required = true)
        protected String city;
        @XmlElement(required = true)
        protected String country;
        protected float latitude;
        protected float longitude;

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         */
        public float getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         */
        public void setLatitude(float value) {
            this.latitude = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         */
        public float getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         */
        public void setLongitude(float value) {
            this.longitude = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="acc_picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accPicture"
    })
    public static class AccPictures {

        @XmlElement(name = "acc_picture", required = true)
        protected List<byte[]> accPicture;

        /**
         * Gets the value of the accPicture property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accPicture property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccPicture().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * byte[]
         * 
         */
        public List<byte[]> getAccPicture() {
            if (accPicture == null) {
                accPicture = new ArrayList<byte[]>();
            }
            return this.accPicture;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="acc_price" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="price_value" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="price_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="price_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accPrice"
    })
    public static class AccPricePlan {

        @XmlElement(name = "acc_price", required = true)
        protected List<Accommodation.AccPricePlan.AccPrice> accPrice;

        /**
         * Gets the value of the accPrice property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accPrice property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccPrice().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Accommodation.AccPricePlan.AccPrice }
         * 
         * 
         */
        public List<Accommodation.AccPricePlan.AccPrice> getAccPrice() {
            if (accPrice == null) {
                accPrice = new ArrayList<Accommodation.AccPricePlan.AccPrice>();
            }
            return this.accPrice;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="price_value" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="price_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="price_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priceValue",
            "priceStartDate",
            "priceEndDate"
        })
        public static class AccPrice {

            @XmlElement(name = "price_value")
            protected float priceValue;
            @XmlElement(name = "price_start_date", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar priceStartDate;
            @XmlElement(name = "price_end_date", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar priceEndDate;

            /**
             * Gets the value of the priceValue property.
             * 
             */
            public float getPriceValue() {
                return priceValue;
            }

            /**
             * Sets the value of the priceValue property.
             * 
             */
            public void setPriceValue(float value) {
                this.priceValue = value;
            }

            /**
             * Gets the value of the priceStartDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPriceStartDate() {
                return priceStartDate;
            }

            /**
             * Sets the value of the priceStartDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPriceStartDate(XMLGregorianCalendar value) {
                this.priceStartDate = value;
            }

            /**
             * Gets the value of the priceEndDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPriceEndDate() {
                return priceEndDate;
            }

            /**
             * Sets the value of the priceEndDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPriceEndDate(XMLGregorianCalendar value) {
                this.priceEndDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}service" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "service"
    })
    public static class AccServices {

        protected List<Service> service;

        /**
         * Gets the value of the service property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the service property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Service }
         * 
         * 
         */
        public List<Service> getService() {
            if (service == null) {
                service = new ArrayList<Service>();
            }
            return this.service;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="unavailable_start" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="unavailable_end" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unavailableStart",
        "unavailableEnd"
    })
    public static class AccUnavailable {

        @XmlElement(name = "unavailable_start", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar unavailableStart;
        @XmlElement(name = "unavailable_end", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar unavailableEnd;

        /**
         * Gets the value of the unavailableStart property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getUnavailableStart() {
            return unavailableStart;
        }

        /**
         * Sets the value of the unavailableStart property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setUnavailableStart(XMLGregorianCalendar value) {
            this.unavailableStart = value;
        }

        /**
         * Gets the value of the unavailableEnd property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getUnavailableEnd() {
            return unavailableEnd;
        }

        /**
         * Sets the value of the unavailableEnd property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setUnavailableEnd(XMLGregorianCalendar value) {
            this.unavailableEnd = value;
        }

    }

}
