//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 08:08:22 PM CEST 
//


package com.megatravel.agentbackend.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acc_type_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="acc_type_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accTypeId",
    "accTypeName"
})
@XmlRootElement(name = "acc_type")
@Entity
public class AccType {
	
	@Id
    @XmlElement(name = "acc_type_id")
    protected long accTypeId;
    @XmlElement(name = "acc_type_name", required = true)
    protected String accTypeName;

    /**
     * Gets the value of the accTypeId property.
     * 
     */
    public long getAccTypeId() {
        return accTypeId;
    }

    /**
     * Sets the value of the accTypeId property.
     * 
     */
    public void setAccTypeId(long value) {
        this.accTypeId = value;
    }

    /**
     * Gets the value of the accTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccTypeName() {
        return accTypeName;
    }

    /**
     * Sets the value of the accTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccTypeName(String value) {
        this.accTypeName = value;
    }

}
