//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 08:08:22 PM CEST 
//


package com.megatravel.agentbackend.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Admin_QNAME = new QName("", "admin");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link Accommodation.AccPricePlan }
     * 
     */
    public Accommodation.AccPricePlan createAccommodationAccPricePlan() {
        return new Accommodation.AccPricePlan();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link AccType }
     * 
     */
    public AccType createAccType() {
        return new AccType();
    }

    /**
     * Create an instance of {@link EndUser }
     * 
     */
    public EndUser createEndUser() {
        return new EndUser();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Review.ReviewComment }
     * 
     */
    public Review.ReviewComment createReviewReviewComment() {
        return new Review.ReviewComment();
    }

    /**
     * Create an instance of {@link Accommodation.AccPictures }
     * 
     */
    public Accommodation.AccPictures createAccommodationAccPictures() {
        return new Accommodation.AccPictures();
    }

    /**
     * Create an instance of {@link Accommodation.AccUnavailable }
     * 
     */
    public Accommodation.AccUnavailable createAccommodationAccUnavailable() {
        return new Accommodation.AccUnavailable();
    }

    /**
     * Create an instance of {@link Accommodation.AccLocation }
     * 
     */
    public Accommodation.AccLocation createAccommodationAccLocation() {
        return new Accommodation.AccLocation();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Accommodation.AccServices }
     * 
     */
    public Accommodation.AccServices createAccommodationAccServices() {
        return new Accommodation.AccServices();
    }

    /**
     * Create an instance of {@link Accommodation.AccPricePlan.AccPrice }
     * 
     */
    public Accommodation.AccPricePlan.AccPrice createAccommodationAccPricePlanAccPrice() {
        return new Accommodation.AccPricePlan.AccPrice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "admin")
    public JAXBElement<User> createAdmin(User value) {
        return new JAXBElement<User>(_Admin_QNAME, User.class, null, value);
    }

}
