//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 08:08:22 PM CEST 
//


package com.megatravel.agentbackend.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for User complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="User">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="u_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="u_username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="u_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="u_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="u_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="u_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", propOrder = {
    "uId",
    "uUsername",
    "uFirstName",
    "uLastName",
    "uPassword",
    "uEmail",
    "activated"
})
@XmlSeeAlso({
    EndUser.class,
    Agent.class
})
@Entity
public abstract class User {

	@Id
    @XmlElement(name = "u_id")
    protected long uId;
    @XmlElement(name = "u_username", required = true)
    protected String uUsername;
    @XmlElement(name = "u_first_name", required = true)
    protected String uFirstName;
    @XmlElement(name = "u_last_name", required = true)
    protected String uLastName;
    @XmlElement(name = "u_password", required = true)
    protected String uPassword;
    @XmlElement(name = "u_email", required = true)
    protected String uEmail;
    @XmlElement(defaultValue = "false")
    protected boolean activated;
    @XmlAttribute(name = "deleted")
    protected Boolean deleted;

    /**
     * Gets the value of the uId property.
     * 
     */
    public long getUId() {
        return uId;
    }

    /**
     * Sets the value of the uId property.
     * 
     */
    public void setUId(long value) {
        this.uId = value;
    }

    /**
     * Gets the value of the uUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUsername() {
        return uUsername;
    }

    /**
     * Sets the value of the uUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUsername(String value) {
        this.uUsername = value;
    }

    /**
     * Gets the value of the uFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUFirstName() {
        return uFirstName;
    }

    /**
     * Sets the value of the uFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUFirstName(String value) {
        this.uFirstName = value;
    }

    /**
     * Gets the value of the uLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getULastName() {
        return uLastName;
    }

    /**
     * Sets the value of the uLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setULastName(String value) {
        this.uLastName = value;
    }

    /**
     * Gets the value of the uPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPassword() {
        return uPassword;
    }

    /**
     * Sets the value of the uPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPassword(String value) {
        this.uPassword = value;
    }

    /**
     * Gets the value of the uEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUEmail() {
        return uEmail;
    }

    /**
     * Sets the value of the uEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUEmail(String value) {
        this.uEmail = value;
    }

    /**
     * Gets the value of the activated property.
     * 
     */
    public boolean isActivated() {
        return activated;
    }

    /**
     * Sets the value of the activated property.
     * 
     */
    public void setActivated(boolean value) {
        this.activated = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDeleted() {
        if (deleted == null) {
            return false;
        } else {
            return deleted;
        }
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleted(Boolean value) {
        this.deleted = value;
    }

}
