
package com.megatravel.agentbackend.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MegaTravelPortService", targetNamespace = "http://megatravel.com/booking/ws", wsdlLocation = "http://localhost:8080/ws/mega-travel-soap.wsdl")
public class MegaTravelPortService
    extends Service
{

    private final static URL MEGATRAVELPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEGATRAVELPORTSERVICE_EXCEPTION;
    private final static QName MEGATRAVELPORTSERVICE_QNAME = new QName("http://megatravel.com/booking/ws", "MegaTravelPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/mega-travel-soap.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEGATRAVELPORTSERVICE_WSDL_LOCATION = url;
        MEGATRAVELPORTSERVICE_EXCEPTION = e;
    }

    public MegaTravelPortService() {
        super(__getWsdlLocation(), MEGATRAVELPORTSERVICE_QNAME);
    }

    public MegaTravelPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEGATRAVELPORTSERVICE_QNAME, features);
    }

    public MegaTravelPortService(URL wsdlLocation) {
        super(wsdlLocation, MEGATRAVELPORTSERVICE_QNAME);
    }

    public MegaTravelPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEGATRAVELPORTSERVICE_QNAME, features);
    }

    public MegaTravelPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MegaTravelPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MegaTravelPort
     */
    @WebEndpoint(name = "MegaTravelPortSoap11")
    public MegaTravelPort getMegaTravelPortSoap11() {
        return super.getPort(new QName("http://megatravel.com/booking/ws", "MegaTravelPortSoap11"), MegaTravelPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MegaTravelPort
     */
    @WebEndpoint(name = "MegaTravelPortSoap11")
    public MegaTravelPort getMegaTravelPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://megatravel.com/booking/ws", "MegaTravelPortSoap11"), MegaTravelPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEGATRAVELPORTSERVICE_EXCEPTION!= null) {
            throw MEGATRAVELPORTSERVICE_EXCEPTION;
        }
        return MEGATRAVELPORTSERVICE_WSDL_LOCATION;
    }

}
