//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 08:07:49 PM CEST 
//


package model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="r_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{}end_user"/>
 *         &lt;element ref="{}accommodation"/>
 *         &lt;element name="r_price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="r_start_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="r_end_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="r_people" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="r_reservation_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="realized" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="cancelled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rId",
    "endUser",
    "accommodation",
    "rPrice",
    "rStartDate",
    "rEndDate",
    "rPeople",
    "rReservationDate"
})
@XmlRootElement(name = "reservation")
public class Reservation {

    @XmlElement(name = "r_id")
    protected long rId;
    @XmlElement(name = "end_user", required = true)
    protected EndUser endUser;
    @XmlElement(required = true)
    protected Accommodation accommodation;
    @XmlElement(name = "r_price")
    protected float rPrice;
    @XmlElement(name = "r_start_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rStartDate;
    @XmlElement(name = "r_end_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rEndDate;
    @XmlElement(name = "r_people", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger rPeople;
    @XmlElement(name = "r_reservation_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rReservationDate;
    @XmlAttribute(name = "realized")
    protected Boolean realized;
    @XmlAttribute(name = "cancelled")
    protected Boolean cancelled;

    /**
     * Gets the value of the rId property.
     * 
     */
    public long getRId() {
        return rId;
    }

    /**
     * Sets the value of the rId property.
     * 
     */
    public void setRId(long value) {
        this.rId = value;
    }

    /**
     * Gets the value of the endUser property.
     * 
     * @return
     *     possible object is
     *     {@link EndUser }
     *     
     */
    public EndUser getEndUser() {
        return endUser;
    }

    /**
     * Sets the value of the endUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUser }
     *     
     */
    public void setEndUser(EndUser value) {
        this.endUser = value;
    }

    /**
     * Gets the value of the accommodation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation }
     *     
     */
    public Accommodation getAccommodation() {
        return accommodation;
    }

    /**
     * Sets the value of the accommodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation }
     *     
     */
    public void setAccommodation(Accommodation value) {
        this.accommodation = value;
    }

    /**
     * Gets the value of the rPrice property.
     * 
     */
    public float getRPrice() {
        return rPrice;
    }

    /**
     * Sets the value of the rPrice property.
     * 
     */
    public void setRPrice(float value) {
        this.rPrice = value;
    }

    /**
     * Gets the value of the rStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRStartDate() {
        return rStartDate;
    }

    /**
     * Sets the value of the rStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRStartDate(XMLGregorianCalendar value) {
        this.rStartDate = value;
    }

    /**
     * Gets the value of the rEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getREndDate() {
        return rEndDate;
    }

    /**
     * Sets the value of the rEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setREndDate(XMLGregorianCalendar value) {
        this.rEndDate = value;
    }

    /**
     * Gets the value of the rPeople property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRPeople() {
        return rPeople;
    }

    /**
     * Sets the value of the rPeople property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRPeople(BigInteger value) {
        this.rPeople = value;
    }

    /**
     * Gets the value of the rReservationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRReservationDate() {
        return rReservationDate;
    }

    /**
     * Sets the value of the rReservationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRReservationDate(XMLGregorianCalendar value) {
        this.rReservationDate = value;
    }

    /**
     * Gets the value of the realized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRealized() {
        if (realized == null) {
            return false;
        } else {
            return realized;
        }
    }

    /**
     * Sets the value of the realized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRealized(Boolean value) {
        this.realized = value;
    }

    /**
     * Gets the value of the cancelled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCancelled() {
        if (cancelled == null) {
            return false;
        } else {
            return cancelled;
        }
    }

    /**
     * Sets the value of the cancelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCancelled(Boolean value) {
        this.cancelled = value;
    }

}
