//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.18 at 08:08:22 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="review_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="review_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="review_grade">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="review_comment">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="approved" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}end_user"/>
 *         &lt;element ref="{}accommodation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reviewId",
    "reviewDate",
    "reviewGrade",
    "reviewComment",
    "endUser",
    "accommodation"
})
@XmlRootElement(name = "review")
public class Review {

    @XmlElement(name = "review_id")
    protected long reviewId;
    @XmlElement(name = "review_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reviewDate;
    @XmlElement(name = "review_grade")
    protected int reviewGrade;
    @XmlElement(name = "review_comment", required = true)
    protected Review.ReviewComment reviewComment;
    @XmlElement(name = "end_user", required = true)
    protected EndUser endUser;
    @XmlElement(required = true)
    protected Accommodation accommodation;

    /**
     * Gets the value of the reviewId property.
     * 
     */
    public long getReviewId() {
        return reviewId;
    }

    /**
     * Sets the value of the reviewId property.
     * 
     */
    public void setReviewId(long value) {
        this.reviewId = value;
    }

    /**
     * Gets the value of the reviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReviewDate() {
        return reviewDate;
    }

    /**
     * Sets the value of the reviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReviewDate(XMLGregorianCalendar value) {
        this.reviewDate = value;
    }

    /**
     * Gets the value of the reviewGrade property.
     * 
     */
    public int getReviewGrade() {
        return reviewGrade;
    }

    /**
     * Sets the value of the reviewGrade property.
     * 
     */
    public void setReviewGrade(int value) {
        this.reviewGrade = value;
    }

    /**
     * Gets the value of the reviewComment property.
     * 
     * @return
     *     possible object is
     *     {@link Review.ReviewComment }
     *     
     */
    public Review.ReviewComment getReviewComment() {
        return reviewComment;
    }

    /**
     * Sets the value of the reviewComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.ReviewComment }
     *     
     */
    public void setReviewComment(Review.ReviewComment value) {
        this.reviewComment = value;
    }

    /**
     * Gets the value of the endUser property.
     * 
     * @return
     *     possible object is
     *     {@link EndUser }
     *     
     */
    public EndUser getEndUser() {
        return endUser;
    }

    /**
     * Sets the value of the endUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndUser }
     *     
     */
    public void setEndUser(EndUser value) {
        this.endUser = value;
    }

    /**
     * Gets the value of the accommodation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation }
     *     
     */
    public Accommodation getAccommodation() {
        return accommodation;
    }

    /**
     * Sets the value of the accommodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation }
     *     
     */
    public void setAccommodation(Accommodation value) {
        this.accommodation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="approved" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ReviewComment {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "approved", required = true)
        protected boolean approved;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the approved property.
         * 
         */
        public boolean isApproved() {
            return approved;
        }

        /**
         * Sets the value of the approved property.
         * 
         */
        public void setApproved(boolean value) {
            this.approved = value;
        }

    }

}
